// Code generated by "stringer -type=Version"; DO NOT EDIT.

package symbol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VM1-0]
	_ = x[VM2-1]
	_ = x[VM3-2]
	_ = x[VM4-3]
	_ = x[V1-4]
	_ = x[V2-5]
	_ = x[V3-6]
	_ = x[V4-7]
	_ = x[V5-8]
	_ = x[V6-9]
	_ = x[V7-10]
	_ = x[V8-11]
	_ = x[V9-12]
	_ = x[V10-13]
	_ = x[V11-14]
	_ = x[V12-15]
	_ = x[V13-16]
	_ = x[V14-17]
	_ = x[V15-18]
	_ = x[V16-19]
	_ = x[V17-20]
	_ = x[V18-21]
	_ = x[V19-22]
	_ = x[V20-23]
	_ = x[V21-24]
	_ = x[V22-25]
	_ = x[V23-26]
	_ = x[V24-27]
	_ = x[V25-28]
	_ = x[V26-29]
	_ = x[V27-30]
	_ = x[V28-31]
	_ = x[V29-32]
	_ = x[V30-33]
	_ = x[V31-34]
	_ = x[V32-35]
	_ = x[V33-36]
	_ = x[V34-37]
	_ = x[V35-38]
	_ = x[V36-39]
	_ = x[V37-40]
	_ = x[V38-41]
	_ = x[V39-42]
	_ = x[V40-43]
}

const _Version_name = "VM1VM2VM3VM4V1V2V3V4V5V6V7V8V9V10V11V12V13V14V15V16V17V18V19V20V21V22V23V24V25V26V27V28V29V30V31V32V33V34V35V36V37V38V39V40"

var _Version_index = [...]uint8{0, 3, 6, 9, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123}

func (i Version) String() string {
	if i < 0 || i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
